version: '3'

services:

  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - proxy_network
    volumes:
      - ./node:/usr/src/app
    #tty: true
    #ports:
    # - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nginx_node_db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - proxy_network

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - proxy_network
    ports:
      - "80:80"
    depends_on:
      - app

networks:
  proxy_network:
    driver: bridge